[package]
name = "faye"
description = "a pretty lil lisp"
authors = ["fawn <fawn@envs.net>"]
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://codeberg.org/fawn/faye"

[dependencies]
clap = { version = "4.4.2", features = ["derive", "cargo"] }
rustyline = "12.0.0"
