[package]
name = "faye"
description = "a pretty lil lisp"
authors = ["fawn <fawn@envs.net>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://codeberg.org/fawn/faye"

[dependencies]
rustyline = "12.0.0"
