steps:
  test:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup component add clippy
      - cargo clippy --verbose --all
      - cargo test --verbose --all
